export const questions = [
    { "key": "1_able", "value": "1. Able - කාර්යශූරය" },
    { "key": "2_brave", "value": "2. Brave - ධෛර්යවන්තය" },
    { "key": "3_clever", "value": "3. Clever - නුවණක්කාරය" },
    { "key": "4_dignified", "value": "4. Dignified - තමාගේ චරිතය පිරිසිදුව තබා ගැනීම ගැන සිතයි" },
    { "key": "5_friendly", "value": "5. Friendly - මිත්‍රශීලීයි" },
    { "key": "6_idealistic", "value": "6. Idealistic - දාර්ශණිකය" },
    { "key": "7_introverted", "value": "7. Introverted - මිනිසුන් සමඟ වැඩි භජනයක් නැත. අභ්‍යන්තරයට හැරුනු චරිතයක් ඇත." },
    { "key": "8_loving", "value": "8. Loving - අන් අයට ආදරය දැක්වීමට සමත්" },
    { "key": "9_observant", "value": "9. Observant - විමර්ෂණශීලී" },
    { "key": "10_proud", "value": "10. Proud - උඩඟුය" },
    { "key": "11_religious", "value": "11. Religious - ආගමික අංශයන්ට බරය" },
    { "key": "12_self_conscious", "value": "12. Self-conscious - තමාගේ සිත ගැන හොඳ අවබෝධයක් ඇත" },
    { "key": "13_silly", "value": "13. Silly - අඥානයි" },
    { "key": "14_trustworthy", "value": "14. Trustworthy - විශ්වාසය තැබිය හැකිය" },
    { "key": "15_accepting", "value": "15. Accepting - වෙනස් කම් නොතකා ඕනෑම කෙනෙක් සාදරයන් පිළිගනි" },
    { "key": "16_calm", "value": "16. Calm - නිවුණු ගති ඇත්තෙකි" },
    { "key": "17_complex", "value": "17. Complex - සංකීර්ණ පුද්ගලයෙකි" },
    { "key": "18_empathetic", "value": "18. Empathetic - අන් අයගේ දුක හඳුනන්නෙකි" },
    { "key": "19_giving", "value": "19. Giving - දානයට ප්‍රියයි" },
    { "key": "20_independent", "value": "20. Independent - අන් අයගේ උදව් නැතිව තමාගේ වැඩ කරගත හැකිය" },
    { "key": "21_kind", "value": "21. Kind - කරුණාවන්තයි" },
    { "key": "22_mature", "value": "22. Mature - පරිණිතයි" },
    { "key": "23_organized", "value": "23. Organized - සංවිධානාත්මකය" },
    { "key": "24_quiet", "value": "24. Quiet - නිශ්ශබ්දය" },
    { "key": "25_responsive", "value": "25. Responsive - ඕනෑම සිදුවීමකදී ඉක්මනින් ඒ සබඳව ප්‍රතිචාර/ ප්‍රතික්‍රියා දක්වන්නෙකි" },
    { "key": "26_sensible", "value": "26. Sensible - ඕනෑම දෙයක් ඉක්මනින් අවබෝධ කරගැනීමට හැකි පුද්ගලයෙකි" },
    { "key": "27_spontaneous", "value": "27. Spontaneous - කලින් සැලසුම් නොකර විවිධ ක්‍රියාකාරකම් වල යෙදින පුද්ගලයෙකි" },
    { "key": "28_warm", "value": "28. Warm - ඉතා හිතවත් කෙනෙකි. අවට සිටින අයට සුරක්ෂිතභාවයක් දැනේ" },
    { "key": "29_adaptable", "value": "29. Adaptable - ඕනෑම අවස්ථාවකට හැඩගැසිය හැකි කෙනෙකි" },
    { "key": "30_caring", "value": "30. Caring - අන් අය ගැන කරුණාවෙන් සොයා බලයි" },
    { "key": "31_confident", "value": "31. Confident - තමා හා තම හැකියාවන් ගැන හොඳ විශ්වාසයක් ඇති කෙනෙකි" },
    { "key": "32_energetic", "value": "32. Energetic - ක්‍රියාශීලීයි" },
    { "key": "33_happy", "value": "33. Happy - නිතරම සතුටින් සිටින්නෙකි" },
    { "key": "34_ingenious", "value": "34. Ingenious - උපායශීලී කෙනෙකි" },
    { "key": "35_knowledgeable", "value": "35. Knowledgeable - විශාල දැනුමකින් පරිපූර්ණ කෙනෙකි" },
    { "key": "36_modest", "value": "36. Modest - නිරහංකාරයි" },
    { "key": "37_patient", "value": "37. Patient - ඉතා ඉවසිලිවන්ත කෙනෙකි" },
    { "key": "38_reflective", "value": "38. Reflective - තමාගේ සිතිවිලි ගැන නිතරම තක්සේරු කරමින් සිටින කෙනෙකි" },
    { "key": "39_searching", "value": "39. Searching - විශ්වය පිළිබඳ සොයමින්, ප්‍රශ්ණ කරමින් සිටින කෙනෙකි" },
    { "key": "40_sentimental", "value": "40. Sentimental - සංවේදී කෙනෙකි" },
    { "key": "41_sympathetic", "value": "41. Sympathetic - අන් අයට අනුකම්පාව දක්වන කෙනෙකි" },
    { "key": "42_wise", "value": "42. Wise - ඇසූ පිරූ තැන් ඇති, ජීවිතාද්දැකීම් ඇති කෙනෙකි" },
    { "key": "43_bold", "value": "43. Bold - ඕනෑම දෙයකට නොබියව මුහුණ දෙන කෙනෙකි" },
    { "key": "44_cheerful", "value": "44. Cheerful - නිතර උද්‍යෝගයෙන් පසුවන කෙනෙකි" },
    { "key": "45_dependable", "value": "45. Dependable - අන් අයට ඔබ කෙරෙහි විශ්වාසය තැබිය හැකියි" },
    { "key": "46_extroverted", "value": "46. Extroverted - මිනිසුන් ආශ්‍රය කිරීම කැමතියි. භාහිරට විහිදුනු සිතක් ඇත්තෙකි" },
    { "key": "47_helpful", "value": "47. Helpful - මිනිසුන්ට උදව් කිරීමට කැමති කෙනෙකි" },
    { "key": "48_intelligent", "value": "48. Intelligent - බුද්ධිමතෙකි" },
    { "key": "49_logical", "value": "49. Logical - තර්කාණුකූල ලෙස සිතන කෙනෙකි" },
    { "key": "50_nervous", "value": "50. Nervous - ඉතා ඉක්මනින් කලබල වෙන කෙනෙකි" },
    { "key": "51_powerful", "value": "51. Powerful - බලවත් කෙනෙකි. සමාජය කෙරෙහි බලපෑමක් ඇති කල හැකි කෙනෙකි" },
    { "key": "52_relaxed", "value": "52. Relaxed - ඉතා සංයමයෙන් ක්‍රියා කරන කෙනෙකි" },
    { "key": "53_self_assertive", "value": "53. Self-assertive - තමාගේ මතය ඉටු කරගනී" },
    { "key": "54_shy", "value": "54. Shy - ලැජ්ජාශීලී කෙනෙකි" },
    { "key": "55_tense", "value": "55. Tense - ආතතියෙන් සිටී" },
    { "key": "56_witty", "value": "56. Witty - අන් අය සිනහ ගැන්වීමට සමත් තැනට සුදුසු මුඛරිකමක් ඇත" },
    { "key": "57_lazy", "value": "57. Lazy - ඉතා කම්මැලි කෙනෙකි" },
    { "key": "58_ability_to_articulate_concepts", "value": "58. Ability to articulate concepts - තම අදහස් ඉතා පැහැදිලිව අන් අය සමඟ බෙදා ගත හැකි කෙනෙකි" },
    { "key": "59_ability_to_multitask", "value": "59. Ability to multitask - එක්වර ක්‍රියා කිහිපයක් සාර්ථකව කල හැකි කෙනෙකි" },
    { "key": "60_ability_to_make_good_decisions", "value": "60. Ability to make good decisions - බුද්ධිමත් ලෙස තීරණ ගැනීමට හැකි කෙනෙකි" },
    { "key": "61_problem_solving_skills", "value": "61. Problem-solving skills - ඕනෑම ප්‍රශ්ණයක් විසඳීමට නිර්මාණශීලී ආකාරයක් සොයා ගනි" },
    { "key": "62_ability_to_manage_people_well", "value": "62. Ability to manage people well - පිරිසක් පාලනය කර කළමණාකරණය කල හැක" },
    { "key": "63_ability_to_manage_resources", "value": "63. Ability to manage resources - මුදල් කළමණාකරණය කල හැක" },
    { "key": "64_integrity", "value": "64. Integrity - කියන දෙය කරන, කරන දෙය කියන ගුණයක් ඇති කෙනෙකි" },
    { "key": "65_leadership_qualities", "value": "65. Leadership qualities - නායකත්ව ගුණ ඇති කෙනෙකි" },
    { "key": "66_organised_and_clean", "value": "66. Organised and clean - තම වටපිටාව පිරිසිදුවට පිළිවෙලට තබා ගන්න කෙනෙකි" },
    { "key": "67_consistent", "value": "67. Consistent - එක් දෙයක් එක දිගට නොකඩවා කිරීමේ හැකියාව ඇත" },
    { "key": "68_driven", "value": "68. Driven - මනස යමකට යෙදවුවොත් වෙහෙස මහන්සිය නොබලා එය අත් පත් කර ගැනීමට වෙහෙසෙන්නෙකි" },
    { "key": "69_can_focus_on_only_one_task_at_a_time", "value": "69. Can focus on only one task at a time. But can do an exceptional job with that task - එක් වරකට කල හැක්කේ එක් දෙයකි නමුත් එය සාර්ථකව ඉටු කරයි." }
] 